name: stunning_octo_invention
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  google_maps_flutter:

  json_annotation:
  json_serializable:

  markdown_widget:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/